<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="Shelter_Hervas.Application\Shelter_Hervas.Application.csproj" />
      <ProjectReference Include="Shelter_Hervas.Domain\Shelter_Hervas.Domain.csproj" />
      <ProjectReference Include="Shelter_Hervas.Infrastructure\Shelter_Hervas.Infrastructure.csproj" />
    </ItemGroup>

</Project>
